ReadArray_HDF5 – SELF
ReadArray_HDF5 Interface
3-Clause BSD with attribution
15 statements
Source File
public interface ReadArray_HDF5
Calls
Called by
Contents
Module Procedures
ReadArray_HDF5_real_r1_serial ReadArray_HDF5_real_r2_serial ReadArray_HDF5_real_r3_serial ReadArray_HDF5_real_r4_serial ReadArray_HDF5_real_r5_serial ReadArray_HDF5_int32_r1_serial ReadArray_HDF5_int32_r2_serial ReadArray_HDF5_real_r1_parallel ReadArray_HDF5_real_r2_parallel ReadArray_HDF5_real_r3_parallel ReadArray_HDF5_real_r4_parallel ReadArray_HDF5_int32_r1_parallel ReadArray_HDF5_int32_r2_parallel
Module Procedures
private subroutine ReadArray_HDF5_real_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:) :: hfArray
private subroutine ReadArray_HDF5_real_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:) :: hfArray
private subroutine ReadArray_HDF5_real_r3_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:) :: hfArray
private subroutine ReadArray_HDF5_real_r4_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:,:) :: hfArray
private subroutine ReadArray_HDF5_real_r5_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:,:,:) :: hfArray
private subroutine ReadArray_HDF5_int32_r1_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
integer(kind=int32), intent(inout), dimension(:) :: hfArray
private subroutine ReadArray_HDF5_int32_r2_serial(fileId, arrayName, hfArray)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
integer(kind=int32), intent(inout), dimension(:,:) :: hfArray
private subroutine ReadArray_HDF5_real_r1_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
private subroutine ReadArray_HDF5_real_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
private subroutine ReadArray_HDF5_real_r3_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:3)
private subroutine ReadArray_HDF5_real_r4_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
real(kind=prec), intent(inout), dimension(:,:,:,:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:4)
private subroutine ReadArray_HDF5_int32_r1_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
integer(kind=int32), intent(inout), dimension(:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1)
private subroutine ReadArray_HDF5_int32_r2_parallel(fileId, arrayName, hfArray, offset)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: fileId
character, intent(in) :: arrayName
integer(kind=int32), intent(inout), dimension(:,:) :: hfArray
integer(kind=HID_T), intent(in) :: offset(1:2)
Call graph
readarray_hdf5 calls readarray_hdf5_real_r2_serial, readarray_hdf5_real_r4_parallel, readarray_hdf5_real_r4_serial, readarray_hdf5_int32_r2_serial, readarray_hdf5_real_r5_serial, readarray_hdf5_int32_r1_parallel, readarray_hdf5_int32_r2_parallel, readarray_hdf5_real_r1_serial, readarray_hdf5_real_r3_serial, readarray_hdf5_int32_r1_serial, readarray_hdf5_real_r1_parallel, readarray_hdf5_real_r2_parallel, readarray_hdf5_real_r3_parallel
readarray_hdf5_real_r2_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_real_r4_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
readarray_hdf5_real_r4_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_int32_r2_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_real_r5_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_int32_r1_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
readarray_hdf5_int32_r2_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
readarray_hdf5_real_r1_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_real_r3_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_int32_r1_serial calls h5dread_f, h5dclose_f, h5dopen_f, h5kind_to_type
readarray_hdf5_real_r1_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
readarray_hdf5_real_r2_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
readarray_hdf5_real_r3_parallel calls h5screate_simple_f, h5dread_f, h5dclose_f, h5dget_type_f, h5sclose_f, h5dopen_f, h5dget_space_f, h5pcreate_f, h5sselect_hyperslab_f, h5pset_dxpl_mpio_f, h5tclose_f, h5pclose_f
read_dgmodel2d_t calls readarray_hdf5
read_dgmodel1d_t calls readarray_hdf5
read_hopr_mesh2d_t calls readarray_hdf5
read_dgmodel3d_t calls readarray_hdf5
read_hopr_mesh3d_t calls readarray_hdf5